In [1]:
import numpy as np

### 1.
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [3]:
## Assuming that N is number of clms = 5 as it is not specified in the problem statement

In [18]:
def powerMatrix(inputVctr, maxPow = 5 , Increasing = True):
    mat = []
    for i in range(maxPow):
        if Increasing:
            mat.append(list(np.array(inputVctr)**i))
        else:
            mat.append(list(np.array(inputVctr)**(maxPow-i-1)))
            
    return np.matrix(mat).transpose() 

In [19]:
a = [1,2,3,4]

In [20]:
powerMatrix(a)

matrix([[  1,   1,   1,   1,   1],
        [  1,   2,   4,   8,  16],
        [  1,   3,   9,  27,  81],
        [  1,   4,  16,  64, 256]], dtype=int32)

In [17]:
powerMatrix(a,Increasing=False)

matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1]], dtype=int32)

### 2.

In [28]:
import numpy as np
def movingAvg(seq,window):
    avgSeq = []
    if len(seq) <= window:
        return np.array(sum(seq)/len(seq))
    else:
        for i in range(len(seq)-window+1):
            avgSeq.append(sum(seq[i:i+window])/window)
    return np.array(avgSeq)
            

In [29]:
movingAvg(list(range(10,110,10)),4)

array([25., 35., 45., 55., 65., 75., 85.])

In [30]:
testSeq = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3
movingAvg(testSeq,window)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])